### ISSUE TITLE
Garbage code is not Dead code

### ISSUE THREAD

**Issue by malwarefrank** [malrev/ABD#6]
Slide 23 states that Garbage/Dead code is code "which runs but does not affect an intended result."  Slide 23 further states, "An insertion of code which does not run is called junk code insertion."  The first statement is inconsistent with the document, "Banescu, A Tutorial on Software Obfuscation, 2017," referenced on slide 15.  Banescu states that dead code is "a branch that is never taken during runtime," and that "garbage code is always executed."

I recommend changing Slide 23 to be consistent with the definitions of Banescu.  For example, remove "/Dead" from the slide title and replace "junk" with "dead" in the statement at the bottom of the slide.

**Comment by ntddk** [comment]
Thank you for taking a look. Updated.
